#! /bin/sh
DIST=dev/main
R=/root/build

LIST="ceph corosync-pve ceph-dkms criu extjs ifupdown2 libjs-qrcodejs libpve-u2f-server-perl libqb librados2-perl lxc novnc-pve proxmox/build proxmox-acme proxmox-apt proxmox-archive-keyring proxmox-backup proxmox-backup-qemu proxmox-i18n proxmox-mini-journalreader proxmox-openid-rs/build proxmox-perl-rs/build proxmox-ve proxmox-widget-toolkit pve-access-control pve-apiclient pve-client pve-cluster pve-common pve-container pve-docs pve-edk2-firmware pve-eslint pve-firewall pve-guest-common pve-ha-manager pve-http-server pve-lxc-syscalld pve-manager pve-qemu pve-rs pve-storage pve-xtermjs pve-server qemu-server spiceterm vncterm pve-kernel repo/external"

for i in ${LIST}
do
	for f in ${R}/${i}/*.deb
	do
		b=$(basename ${f})
		case ${b} in
			*dbgsym*|*_amd64.deb|*dbg_*) ;;
			*_arm64.deb) rsync -ptog ${f} ${DIST}/binary-arm64/${b} ;;
			*_all.deb) rsync -ptog ${f} ${DIST}/binary-all/${b} ;;
			*) ;;
		esac
	done
done
