#! /bin/sh
DIST=dev/main
R=/root/build

LIST="ceph corosync-pve criu ifupdown2 libpve-u2f-server-perl libqb librados2-perl lxc novnc-pve proxmox-archive-keyring proxmox-i18n proxmox-mini-journalreader proxmox-widget-toolkit pve-access-control pve-client pve-cluster pve-common pve-container pve-docs pve-firewall pve-guest-common pve-ha-manager pve-http-server pve-lxc-syscalld pve-manager pve-qemu pve-rs pve-storage pve-xtermjs pve-server spiceterm vncterm"

for i in ${LIST}
do
	for f in ${R}/${i}/*.deb
	do
		b=$(basename ${f})
		case ${b} in
			*dbgsym*|*_amd64.deb|*dbg_*) ;;
			*_arm64.deb) rsync -ptog ${f} ${DIST}/binary-arm64/${b} ;;
			*_all.deb) rsync -ptog ${f} ${DIST}/binary-all/${b} ;;
			*) ;;
		esac
	done
done
